### ISSUE TITLE
local variable 'path' referenced before assignment

### ISSUE THREAD

**Issue by Poppy4566** [tagucci/pythonrouge#12]
Hi, I got a problem when I try to evaluate ROUGE scripts in a standard way, for files.

I just run as in readme,and defined  summary_dir & reference_dir, it happens when setting_files:

>>> setting_file = rouge.setting(files=True, summary_path=summary_dir, reference_path=reference_dir)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pythonrouge/pythonrouge.py", line 107, in setting
    file_name = os.path.splitext(os.path.basename(path))[0]
UnboundLocalError: local variable 'path' referenced before assignment

Hope for help, thx!

**Comment by Sukanya-Kudi** [comment]
You need to give absolute path.

**Comment by tagucci** [comment]
sorry  for the late response, I've already fix this issue.
