### ISSUE TITLE
utf8 & pythonrouge

### ISSUE THREAD

**Issue by MahdiDoost** [tagucci/pythonrouge#16]
In the name of GOD
Hello,
Does it program support from Persian language?
Thank you

**Comment by tagucci** [comment]
sorry for the late response. now i plan to evaluate other languages such as japanese. I will implement this in two weeks.

**Comment by MahdiDoost** [comment]
In the name of God
Hello
Thank you for answering.
I wait for your plan for Farsi language.

**Comment by MahdiDoost** [comment]
In the name of Allah
Hello,
I want to customize your program for persian language.
May you help me?
Thank you very much.

**Comment by tagucci** [comment]
sorry for the late response.
I added new example code ([example_ja.py](https://github.com/tagucci/pythonrouge/blob/master/example_ja.py)) to evaluate japanese summary. this may help you to evaluate farsi language!
