### ISSUE TITLE
eval_rouge

### ISSUE THREAD

**Issue by MahdiDoost** [tagucci/pythonrouge#21]
In the name of Allah
Hello,
Thank you for adding japanese summary.
Before I use 'eval_rouge' method but In new code, 'eval_rouge' method don 't exist.
If I want to use new code, must I change perviouse code?
Thank you very much.

**Comment by tagucci** [comment]
yes, you should use new version of pythonrouge.
clone this repository again, or `git pull origin master` will solve your problem:)

**Comment by MahdiDoost** [comment]
In the name of Allah
Hello,
Thank you.

**Comment by Francescobovo** [comment]
Hi, I have a similar issue, when I run the following code to evaluate Rouge I get the error `AttributeError: 'Pythonrouge' object has no attribute 'setting'` cause, of course, there is no _setting_ method nor _eval_rouge_ method. How should i fix it? 

`   
    ROUGE_path = "rouge_files/ROUGE-1.5.5/ROUGE-1.5.5.pl"
    data_path = "rouge_files/ROUGE-1.5.5/data/"

    # initialize setting of ROUGE, eval ROUGE-1, 2
    rouge = Pythonrouge(n_gram=ngram,
                        ROUGE_SU4=False,
                        ROUGE_L=False,
                        stemming=stemming,
                        stopwords=stopwords,
                        word_level=True,
                        length_limit=True,
                        length=100,
                        use_cf=use_cf,
                        cf=95,
                        scoring_formula="average",
                        resampling=True,
                        samples=1000,
                        favor=True,
                        p=0.5)

    # system summary: list of summaries, where each summary is a list of sentences
    summary = [system_summary]

    # reference summaries: list of (list of summaries per article), where each summary is a list of sentences
    reference = [[[summary] for summary in reference_summaries]]

    setting_file = rouge.setting(files=False, summary=summary, reference=reference, temp_root='')

    result = rouge.eval_rouge(setting_file, ROUGE_path=ROUGE_path, data_path=data_path)

    return result`
