### ISSUE TITLE
stemming , stop word In japanese

### ISSUE THREAD

**Issue by MahdiDoost** [tagucci/pythonrouge#22]
In the name of Allah
Hello,
Do can I set stemming , stop word on True In japanese summary?
Thank you very much.

**Comment by MahdiDoost** [comment]
In the name of Allah.
Hello,

>  Do can I set stemming , stop word on True In japanese summary?

I stemming and remove stop words before using pythonrouge.

**Comment by tagucci** [comment]
Evaluation by stemming or stop words removal can be used only in English.
If you want to eval summaries by stemming or stop words removal, please process your summaries by yourself before pythonrouge calculation.

**Comment by MahdiDoost** [comment]
In the name of Allah
Hello,

Thank you very much.
