### ISSUE TITLE
I am wondering the progress of supporting Chinese

### ISSUE THREAD

**Issue by memeda** [tagucci/pythonrouge#25]
Oh, It is so nice to see the repo.

I am puzzled that Whether the original ROUGE perl scripts could support Chinese or other non-ascii characters, or how can I do something to make it support.

I'm surprised to see that very little informations about ROUGE for Unicode, it make the `text summarization` likes self-deception because the Most important Evaluation is supported so bad.

**Comment by tagucci** [comment]
Thanks for a comment:)

As you said, ROUGE only can deal with English or other languages with ascii characters.
If you want to evaluate ROUGE score using original perl scripts, you need to convert word to word_ids (for example, '我' -> 1 ', '你' -> 2). There are no official way to evaluate ROUGE score of non-ascii characters, but I think evaluating ROUGE after converting words to word_ids is one of the ways.

In git repo, I provide sample scripts for non-ascii characters (I evaluate ROUGE score of Japanese summary).

However, if you want to evalaute ROUGE score based on stemming or stopwords_removal as the evaluation of English summarization does, you need to such preprocesses before converting words to word_ids.

**Comment by memeda** [comment]
Nice~ a great way.
