### ISSUE TITLE
I encountered the following problem

### ISSUE THREAD

**Issue by lqjsurpass** [tagucci/pythonrouge#27]
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-3-58c790cf76f2> in <module>()
     17                         use_cf=False, cf=95, scoring_formula='average',
     18                         resampling=True, samples=1000, favor=True, p=0.5)
---> 19     score = rouge.calc_score()
     20     print('ROUGE-N(1-2) & SU4 F-measure only')
     21     pprint(score)

/notebooks/pythonrouge-master/pythonrouge/pythonrouge.py in calc_score(self)
    332     def calc_score(self):
    333         rouge_cmd = self.set_command()
--> 334         output = subprocess.check_output(rouge_cmd, stderr=subprocess.STDOUT)
    335         output = output.decode('utf-8')
    336         output = output.strip().split('\n')

/usr/lib/python3.5/subprocess.py in check_output(timeout, *popenargs, **kwargs)
    624 
    625     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
--> 626                **kwargs).stdout
    627 
    628 

/usr/lib/python3.5/subprocess.py in run(input, timeout, check, *popenargs, **kwargs)
    706         if check and retcode:
    707             raise CalledProcessError(retcode, process.args,
--> 708                                      output=stdout, stderr=stderr)
    709     return CompletedProcess(process.args, retcode, stdout, stderr)
    710 

CalledProcessError: Command '['perl', '/notebooks/pythonrouge-master/pythonrouge/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', '/notebooks/pythonrouge-master/pythonrouge/RELEASE-1.5.5/data', '-a', '-n', '2', '-2', '4', '-u', '-x', '-l', '50', '-m', '-s', '-f', 'A', '-r', '1000', '-p', '0.5', '/tmp/tmpjkiz4uvr/setting.xml']' returned non-zero exit status 2

Thanks very much！

**Comment by lqjsurpass** [comment]
I run the example.py

**Comment by nana1205** [comment]
楼上您好，可以向您请教几个问题吗？

**Comment by tianyudota** [comment]
Did you solve this problem?

**Comment by elhele** [comment]
I have the same problem. Did anyone solve it?

**Comment by neverfox** [comment]
Same issue. Is there more that's need to get it to work that just installing this package?

**Comment by KTH1234** [comment]
I solved this problem by installing xml parser.

https://stackoverflow.com/questions/9693031/how-to-install-xmlparser-without-expat-devel
