### ISSUE TITLE
Find error when i run the example

### ISSUE THREAD

**Issue by McVilla** [tagucci/pythonrouge#3]
from pythonrouge import pythonrouge

ROUGE = '~/pythonrouge/pythonrouge/RELEASE-1.5.5/ROUGE-1.5.5.pl'

data_path = '~/pythonrouge/pythonrouge/RELEASE-1.5.5/data' #data folder in RELEASE-1.5.5

peer = " Tokyo is the one of the biggest city in the world."

model = "The capital of Japan, Tokyo, is the center of Japanese economy."

score = pythonrouge.pythonrouge(peer, model,"~/pythonrouge/pythonrouge/RELEASE-1.5.5/ROUGE-1.5.5.pl", "~/pythonrouge/pythonrouge/RELEASE-1.5.5/data")

print(score)

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-9-aa0cdffbdee2> in <module>()
      4 peer = " Tokyo is the one of the biggest city in the world."
      5 model = "The capital of Japan, Tokyo, is the center of Japanese economy."
----> 6 score = pythonrouge.pythonrouge(peer, model,"~/pythonrouge/pythonrouge/RELEASE-1.5.5/ROUGE-1.5.5.pl", "~/pythonrouge/pythonrouge/RELEASE-1.5.5/data")
      7 print(score)

/afs/inf.ed.ac.uk/user/s15/s1537328/MSc/env/lib/python2.7/site-packages/pythonrouge/pythonrouge.pyc in pythonrouge(peer_sentence, model_sentence, ROUGE_path, data_path)
     61 
     62     abs_xml_path = str(temp_dir+"/"+xml_path)
---> 63     output = subprocess.check_output([ROUGE_path, "-e", data_path, "-a", "-m", "-2", "4","-n", "3", abs_xml_path], stderr=subprocess.STDOUT)
     64     output = output.decode("utf-8")
     65     outputs = output.strip().split("\n")

/usr/lib64/python2.7/subprocess.pyc in check_output(*popenargs, **kwargs)
    566     if 'stdout' in kwargs:
    567         raise ValueError('stdout argument not allowed, it will be overridden.')
--> 568     process = Popen(stdout=PIPE, *popenargs, **kwargs)
    569     output, unused_err = process.communicate()
    570     retcode = process.poll()

/usr/lib64/python2.7/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
    709                                 p2cread, p2cwrite,
    710                                 c2pread, c2pwrite,
--> 711                                 errread, errwrite)
    712         except Exception:
    713             # Preserve original exception in case os.close raises.

/usr/lib64/python2.7/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, to_close, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
   1325                         raise
   1326                 child_exception = pickle.loads(data)
-> 1327                 raise child_exception
   1328 
   1329 

OSError: [Errno 2] No such file or directory

**Comment by tagucci** [comment]
Sorry for the late response. You should specify full path of ROUGE_path and data_path. However, I fixed pythonrouge.py to set ROUGE_path and data_path as default (you can also specify those path in arguments of pythonrouge function). So you can evaluate not to specify ROUGE/data paths. I modified example.py, so please check it.
