### ISSUE TITLE
CalledProcessError 

### ISSUE THREAD

**Issue by sajastu** [tagucci/pythonrouge#31]
Hi,

I'm getting this error when trying to evaluate on my dev set. Does anybody have idea why this happens?? and solution to it?

Thanks!

> Traceback (most recent call last):
>   File "train.py", line 149, in <module>
>     rouge1, rouge2, rougel = rouge.get_rouge(dev_preds, dev_gold, use_cf=False)
>   File "/disk1/sajad/private/summarize-radiology-findings-normal/utils/rouge.py", line 29, in get_rouge
>     score = rouge.calc_score()
>   File "/home/sajad/anaconda3/lib/python3.6/site-packages/pythonrouge/pythonrouge.py", line 382, in calc_score
>     output = ç.check_output(rouge_cmd, stderr=subprocess.STDOUT)
>   File "/home/sajad/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
>     **kwargs).stdout
>   File "/home/sajad/anaconda3/lib/python3.6/subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['perl', '/home/sajad/anaconda3/lib/python3.6/site-packages/pythonrouge/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', '/home/sajad/anaconda3/lib/python3.6/site-packages/pythonrouge/RELEASE-1.5.5/data', '-a', '-n', '2', '-f', 'A', '-r', '1000', '-p', '0.5', '/tmp/tmp0dq087zw/setting.xml']' returned non-zero exit status 2.
>

**Comment by ixlan** [comment]
same here

**Comment by ixlan** [comment]
The solution to the problem:
$ apt-get install -y cpanminus
$ cpanm --force XML::Parser

**Comment by jpilaul** [comment]
I had to do this as well as ixlan's solution:
apt-get update
apt-get install expat
apt-get install libexpat1-dev

**Comment by Ontheroad123** [comment]
> The solution to the problem:
> $ apt-get install -y cpanminus
> $ cpanm --force XML::Parser
I tried you way,it still errored

**Comment by Ontheroad123** [comment]
if my computer is centos, how can i slove it ?

**Comment by iofu728** [comment]
> > if my computer is centos, how can i slove it ?
> 
> ## There are some error because of lacking some modules. You can find this modules name from 'perl xxxx'

Wa, Thank you old brother🤓

**Comment by Ontheroad123** [comment]
> > > if my computer is centos, how can i slove it ?
> > 
> > 
> > There are some error because of lacking some modules. You can find this modules name from 'perl xxxx'
> 
> Wa, Thank you old brothernerd_face

give detail errors

**Comment by iofu728** [comment]
> give detail errors

I have solved this errors by your method. You're right. Thx🙇

**Comment by sajastu** [comment]
I followed the official perl instructions in the repo under `/pythonrouge/RELEASE-1.5.5` directory. In the meantime, it turned out that there are some dependencies I hadn't have installed, so after conda-installing them, everything just got working! 

You'll be able to figure out what packages (dependencies) your system lacks, but for me, I did the following:

- I re-generate the WordNet-2.0.exc.db database. You'd need to remove, and then re-generate it in this way: 
```
cd pythonrouge/RELEASE-1.5.5/data/
rm WordNet-2.0.exc.db
./WordNet-2.0-Exceptions/buildExeptionDB.pl ./WordNet-2.0-Exceptions ./smart_common_words.txt ./WordNet-2.0.exc.db
```

- I then installed XML::DOM with `cpan XML::DOM`

- I create an environment variable and put its pointing address to /data directory: `ROUGE_EVAL_HOME=/usr/local/ROUGE-1.5.4/data`

- Then `perl ROUGE-1.5.4.pl`. If you have all the perl required dependencies installed, you should be fine, but if you don't, by running this perl script, you'd be able to figure out what you're missing.

Hope this would help!
