### ISSUE TITLE
CalledProcessError : returned non-zero exit status

### ISSUE THREAD

**Issue by metalaman** [tagucci/pythonrouge#4]
line 65 in pythonrouge.py gives the following error when I run example.py:

subprocess.CalledProcessError: Command '['/home/aman/Desktop/pythonrouge-master/pythonrouge/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', '/home/aman/Desktop/pythonrouge-master/pythonrouge/RELEASE-1.5.5/data', '-a', '-m', '-2', '4', '-n', '3', '/tmp/tmp_RW8QT/rouge.xml']' returned non-zero exit status 255

**Comment by tagucci** [comment]
I can't reproduce the error you mentioned. Can you share more details such as input strings of pythonrouge function when error occured?

**Comment by theanirudhvyas** [comment]
The example file "example.py" throws this error.

**Comment by tagucci** [comment]
it may be occurred by wordnet database error.
you can run example.py by doing below.
``
cd pythonrouge/RELEASE-1.5.5/data/
rm WordNet-2.0.exc.db
./WordNet-2.0-Exceptions/buildExeptionDB.pl ./WordNet-2.0-Exceptions ./smart_common_words.txt ./WordNet-2.0.exc.db
``

**Comment by metalaman** [comment]
It worked!
Thank you.

**Comment by JoanZhou** [comment]
thanks!

**Comment by Li-Ming-Fan** [comment]
> It seems don't work for me. Is there another solution?

I have checked the following situation.
If there are some model results are far from the references and share NO common words,
then the above error will occur.

**Comment by RafaelWO** [comment]
This error also occurs if there are some unwanted characters in either the system or model summaries.
In my case it was the token "<unk>" which caused this error. I simply replaced it by "UNK".
