### ISSUE TITLE
how to test rouge for a file

### ISSUE THREAD

**Issue by apeterswu** [tagucci/pythonrouge#6]
Hi, 

Thanks for your script, it can be work very well for one sentence, I have a question that if I have a system sentences file, and a model sentences file, each system corresponding to one model sentence, how to test it with this great package?

**Comment by pltrdy** [comment]
Hi,

I actually used this package to build my `files2rouge` script which exactly does what you need.
You can find it here: https://github.com/pltrdy/files2rouge

**Comment by tagucci** [comment]
Sorry for the late response.
I updated pythonrouge for needs to evaluate ROUGE in a standard way! You can evaluate ROUGE score not just based on sentence lists of system/reference sumamries, but also based on files in specific directories. In details, please read README and example code.
