### ISSUE TITLE
ROUGE-SU4 is actually ROUGE-S4

### ISSUE THREAD

**Issue by pltrdy** [tagucci/pythonrouge#7]
Hey!

Your calling ROUGE-SU4 score which in fact is ROUGE-S4 score. 
Check: https://github.com/tagucci/pythonrouge/blob/master/pythonrouge/pythonrouge.py#L75

**Comment by tagucci** [comment]
thanks for pointing out! pythonrouge is now majority updated for evaluating ROUGE-N, L, SU4 and you can flexible change options such as length-limit or bytes/words level and so on.
