### ISSUE TITLE
example.py issue

### ISSUE THREAD

**Issue by omnyakhaled** [tagucci/pythonrouge#9]
hi 
sorry but when i run the code , i found this error.
Traceback (most recent call last):
  File "C:\Users\omneya\Desktop\bachelor\pythonrouge-master\example.py", line 17, in <module>
    print(rouge.eval_rouge(setting_file, ROUGE_path=ROUGE_path, data_path=data_path))
  File "C:\Users\omneya\Desktop\bachelor\pythonrouge-master\pythonrouge\pythonrouge.py", line 158, in eval_rouge
    output  = subprocess.check_output(rouge_cmd, stderr=subprocess.STDOUT)
  File "C:\Python27\lib\subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['perl', 'C:\\Users\\omneya\\Desktop\\bachelor\\pythonrouge-master\\pythonrouge\\RELEASE-1.5.5\\ROUGE-1.5.5.pl', '-e', 'C:\\Users\\omneya\\Desktop\\bachelor\\pythonrouge-master\\.C:\\Users\\omneya\\Desktop\\bachelor\\pythonrouge-master\\pythonrouge\\RELEASE-1.5.5\\data', '-a', '-n', '2', '-2', '4', '-u', '-l', '50', '-m', '-s', '-f', 'A', '-r', '1000', '-p', '0.5', 'c:\\users\\public\\documents\\wondershare\\creatortemp\\tmpgbsz5p\\setting.xml']' returned non-zero exit status 2

**Comment by hantek** [comment]
Hey, I am getting exactly the same error. Does someone happen to know what is the culprit there?

**Comment by hantek** [comment]
By running the perl command (which is generated by python script) directly on bash, I get this error msg:

$ perl /u/linzhou/tmp/pythonrouge/pythonrouge/RELEASE-1.5.5/ROUGE-1.5.5.pl -e /u/linzhou/tmp/pythonrouge/pythonrouge/RELEASE-1.5.5 -a -n 2 -2 4 -u -l 50 -m -s -f A -r 1000 -p 0.5 /Tmp/linzhou/tmpNPYnz8/setting.xml
Cannot open /u/linzhou/tmp/pythonrouge/pythonrouge/RELEASE-1.5.5/smart_common_words.txt

**Comment by hantek** [comment]
NVM, it's in the ``data`` subfolder

**Comment by Codelegant92** [comment]
I met the same problem. Does anyone solve it? Or are these codes not used any more?

**Comment by tagucci** [comment]
Sorry for the late response.
Did you try the below command in readme?
```
cd pythonrouge/RELEASE-1.5.5/data/
rm WordNet-2.0.exc.db
./WordNet-2.0-Exceptions/buildExeptionDB.pl ./WordNet-2.0-Exceptions ./smart_common_words.txt ./WordNet-2.0.exc.db
```

**Comment by Codelegant92** [comment]
@tagucci 
Yes, it works. Thank you very much!

**Comment by geneforturing** [comment]
Sorry for asking, but I got the same error even though I removed `WordNet-2.0.exc.db` and ran `./WordNet-2.0-Exceptions/buildExeptionDB.pl ./WordNet-2.0-Exceptions ./smart_common_words.txt ./WordNet-2.0.exc.db`.

I executed the test code on github, and environment is python 3.5 on virtualenv. 
Here is the error message:
`(env35) jwy@ai3:~$ python sample.py 
Traceback (most recent call last):
  File "sample.py", line 17, in <module>
    score = rouge.calc_score()
  File "/home/jwy/venv/env36/lib/python3.5/site-packages/pythonrouge-0.1-py3.5.egg/pythonrouge/pythonrouge.py", line 335, in calc_score
    output = subprocess.check_output(rouge_cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['perl', '/home/jwy/venv/env36/lib/python3.5/site-packages/pythonrouge-0.1-py3.5.egg/pythonrouge/RELEASE-1.5.5/ROUGE-1.5.5.pl', '-e', '/home/jwy/venv/env36/lib/python3.5/site-packages/pythonrouge-0.1-py3.5.egg/pythonrouge/RELEASE-1.5.5/data', '-a', '-n', '2', '-2', '4', '-u', '-x', '-l', '50', '-m', '-s', '-f', 'A', '-r', '1000', '-p', '0.5', './tmpmo_p4q7k/setting.xml']' returned non-zero exit status 2`
